# Generated by Django 5.1.3 on 2024-11-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
